metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: true
    reload.period: 10s

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - filesystem
    - fsstat
  enabled: true
  period: 10s
  processes: ['.*']

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true

setup.template.name: "metricbeat-8.12.1"
setup.template.pattern: "metricbeat-8.12.1-*"
setup.template.enabled: true
setup.template.overwrite: true
setup.ilm.enabled: true
setup.ilm.rollover_alias: "metricbeat-8.12.1"
setup.ilm.pattern: "{now/d}-000001"

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~
  - add_kubernetes_metadata: ~

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  indices:
    - index: "metricbeat-8.12.1-%{+yyyy.MM.dd}"
  pipeline: "metricbeat-8.12.1"

logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/metricbeat/logs
  name: metricbeat
  keepfiles: 7
  permissions: 0644 