metricbeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml

metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - filesystem
    - fsstat
  enabled: true
  period: 10s

- module: docker
  metricsets:
    - container
    - cpu
    - diskio
    - event
    - healthcheck
    - info
    - memory
    - network
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s

processors:
  - add_host_metadata: ~
  - add_docker_metadata: ~
  - add_cloud_metadata: ~

output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOSTS}"]
  index: "metricbeat-%{+yyyy.MM.dd}"

setup.kibana:
  host: "${KIBANA_HOSTS}"

setup.template.name: "metricbeat"
setup.template.pattern: "metricbeat-*"
setup.template.enabled: true
setup.template.overwrite: true
setup.ilm.enabled: false 